### ISSUE TITLE
Font fallback stack doesn't make sense

### ISSUE THREAD

**Issue by bowenli** [weaveworks/ui-components#216]
https://github.com/weaveworks/ui-components/blob/master/src/theme/fonts.js#L13

``` "'proxima-nova', sans-serif, 'Helvetica Neue', Helvetica, Arial, sans-serif";```

san-serif needs to be de-duped and last. Since we are hard loading Proxima Nova, we can drop the other ones. The system default san-serif for Mac/Windows is already Helvetica/Arial.

**Comment by bowenli** [comment]
cc @fbarl

**Comment by fbarl** [comment]
I'm just fixing this as a part of #212.

Wouldn't drop `'Helvetica Neue'` part because I wouldn't want to make assumptions here on how the theme is used elsewhere (e.g. are both `scope` and `service-ui` loading `proxima-nova`?).

> The system default san-serif for Mac/Windows is already Helvetica/Arial.

Again, for the reasons above, I'd keep both just in case, even though I don't feel too strongly about it.

**Comment by bowenli** [comment]
Scope standalone is loading Roboto. (https://github.com/weaveworks/scope/blob/7384e24e6382d04aa73c3c8faa78dc20e3e89b55/client/app/styles/_variables.scss)
![screen shot 2018-05-16 at 07 15 19](https://user-images.githubusercontent.com/915421/40122624-1694bc7c-58d9-11e8-8240-7a45960e6d50.png)

![screen shot 2018-05-16 at 07 13 13](https://user-images.githubusercontent.com/915421/40122424-a3db0664-58d8-11e8-99c4-3492ec0764a3.png)

I guarantee you 99.9% of people cannot tell the difference between Helvetica Neue and Helvetica. You can blame me if someone complains.
