### ISSUE TITLE
Export linting rules

### ISSUE THREAD

**Issue by fbarl** [weaveworks/ui-components#255]
Currently we're using separate (although similar) linting rules between our UI repos. It would be good to have one source of truth for all the repos: `ui-components`, `scope`, `service-ui`, for obvious styling reasons as well as for `service-ui` proxying to work smoothly - see https://github.com/weaveworks/service-ui/issues/2495#issue-321155370.

@foot and I talked about it and we thought it would be good to start with `ui-components` repo exporting its rules and then using them in `scope` and `service-ui`. Later on, we might want to move the rules into a separate repo.

The files that we'd need to export:

* `.eslintrc`
* `.stylelintrc`
* `.sass-lint.yml`?

**Comment by guyfedwards** [comment]
Previously I have had success with creating a custom preset `eslint-preset-weaveworks` wrapping all this up. I also creates a forum for people to propose changes to the linting rather than additions being lost within other PRs.

Same for stylelint, we might be able to bundle `.sass-lint.yml` in there as well so that all style linting is in one package.
